name: Deploy to Heroku

on:
  workflow_dispatch:
env:
  EMAIL: "naicoi@lttech.vn"
  APP_NAME: "api-task-techio"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      ### ⬇ IMPORTANT PART ⬇ ###
      - name: Install Heroku CLI # <- IMPORTANT!!! Make sure the cli is installed before using the action
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - uses: akhileshns/heroku-deploy@v3.14.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{env.APP_NAME}}
          heroku_email: ${{env.EMAIL}}
          usedocker: true

      ### ⬆ IMPORTANT PART ⬆ ###
