name: Deploy to Heroku

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      ### ⬇ IMPORTANT PART ⬇ ###

      - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v3.1.0 # use the latest version of the action
        with:
          email: "naicoi@lttech.vn"
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: "api-task-techio" #Must be unique in Heroku
          dockerfile_path: "."
          process_type: web

      ### ⬆ IMPORTANT PART ⬆ ###
